### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Aomitsu** [Ech-app/harid#1]
**Epic roadmap** without any dates lol. ( Not complete )

## Client
- [ ] Map render
  - [ ] Walls
  - [ ] Props
  - [ ] Room size modifier
  - [ ] Multiple floors
  - [ ] Scripting support
- [ ] Game core
  - [ ] In-Game Chat
  - [ ] Friends
  - [ ] Rooms permissions
  - [ ] Moderation
  - [ ] Multiplayer lmao
- [ ] Tools
  - [ ] Model viewer ( `Model = user assets, props, etc...` )
  - [ ] Model creator
  - [ ] Map editor ( For usage out of the game : events, etc... | Something "pro" )
- [ ] Platforms
  - [ ] Web
  - [x] Linux
  - [ ] Windows
  - [ ] Mac OS ( what is that ?? )
  - [ ] Real life.
## Server**s**
- [ ] Rooms
  - [ ] Multiple rooms
  - [ ] Create and Edit rooms
  - [ ] Rooms permission
  - [ ] Database
  - [ ] Cache
- [ ] Game core
  - [ ] In-Game Chat
  - [ ] Friends
  - [ ] Moderation ( Auto )
  - [ ] **DECENTRALIZED**
  - [ ] Multiplayer ( All 'protocols' for naia )
- [ ] Auth Server
  - [ ] Website
  - [ ] REST Api
    - [ ] Login
    - [ ] Register
    - [ ] Get token
    - [ ] Check token ( server login )
    - [ ] etc...
- [ ] UGC Server
  - [ ] Website
  - [ ] Models uploader and check
  - [ ] Moderation ( manual and auto )
  - [ ] Economy ??? ( Can be difficult with decentralized, except if auth server is not decentralized and manage money )
  - [ ] **DECENTRALIZED**
## VERY Long term
- [ ] Our own network lib
- [ ] Our own tilemap lib
- [ ] A cool community
- [x] Entirely free game ( no F2P, P2W, or anything else, just free. )

Can be modified, it's a lot of ideas, maybe this game can't be finished because of that. I'm the worst dev ever, so please help me.. <3
